### ISSUE TITLE
Connection refused, Error: Init Chain

### ISSUE THREAD

**Issue by voidcpp94** [ethersphere/bee-clef#48]
Hello everyone,
I've installed Bee several times (with Bee Clef) and tried to set it up. Unfortunately I can't connect to the Bee service because of "Error: init chain: dial eth client: dial tcp [::1]:8546: connect: connection refused". I've tried to set up a port and to determine the NAT exposed adress. Thats my IPv4 right? The log also says clef is not enabled, but my systemctl status says it is running and active. Pls help

**Comment by vandot** [comment]
Hi @voidcpp94 probably you didn't specified existing blockchain endpoint as described in [docs](https://docs.ethswarm.org/docs/installation/install#blockchain-endpoints)
I will close this issue because it has nothing to do with clef project, please access our community at [Discord](https://discord.gg/GU22h2utj6), right place for this kind of issues
